name: Whl&Build install
on: push
jobs:
  download_and_install:
    runs-on: ubuntu-latest
    needs: Awesome Calculator CI build  # If the artifact was uploaded in a different job
    steps:
      - name: Download .whl artifact
        uses: actions/download-artifact@v4
        with:
          name: your-whl-artifact-name # The name given when uploading the artifact
          path: ./downloaded-whl 
