name: Whl&Build install
on: 
  workflow_run:
    workflows: ["Awesome Calculator CI build"]
    types: completed
  
jobs:
  download_and_install_whl:
      runs-on: ubuntu-latest
      steps:
          - name: Download .whl artifact
            uses: actions/download-artifact@v4
            with:
                name: awesome-calculator # The name given when uploading the artifact
                run-id: ${{ github.event.workflow_run.id }}
                path: src/dist 
          
          - name: Install .whl artifact  
            run: |
              pip install src/dist/*.whl 
