name: Whl&Build install
on: push
jobs:
  download_and_install:
    runs-on: ubuntu-latest
    needs: Awesome Calculator CI build  # The Name of the Previous Workflow Job
    steps:
      - name: Download .whl artifact
        uses: actions/download-artifact@v4
        with:
          name: awesome-calculator # The name given when uploading the artifact
          path: ./downloaded-whl 
